### ISSUE TITLE
Having COVID vs Being infected

### ISSUE THREAD

**Issue by saraedum** [microcovid/microcovid#467] opened 2020-11-03 15:08 UTC
I am working on a translation to German of the calculator. This got me wondering whether the wording of "having COVID" could be improved a bit. It's my understanding that COVID is the name of the disease whereas the virus is called SARS-CoV-2 officially. While lots of people use these two terms interchangeably, a sentence such as "A person at this activity with COVID would have a 0.08% chance of transmitting it to you" should maybe read "A person at this activity with a SARS-CoV-2 infection would have a 0.08% chance of transmitting it to you" (ok, you could even go as far as writing "a person at this activity who is infectious with SARS-CoV-2…" but that's probably overdoing it a bit.)

This is basically an issue in two places:
* In the "How this was calculated" box. It's my impression that this box is a bit for the geeks, so using exact wording probably makes sense?
* In the "Risk profile". Not sure whether it's worth changing the wording here. But maybe it could say "Has the COVID virus" instead of "Has COVID".

That said, this is not really important. Just something that got me thinking whether things could be improved. Thanks a lot for this helpful tool :)

**Comment by blanchardjeremy** [comment] 2020-11-03 21:15
I'll defer to others on the team for this one: @beshaya ? others?

**Comment by me-and** [comment] 2020-11-03 22:11
(Not on the team, but I think I have the context to have an opinion.)

I can't speak for other languages, but I know the World Health Organisation in English only uses SARS-CoV-2 or similar in articles that are intended solely for an audience of medical professionals. At least in the UK, I expect most people won't have seen the term SARS-CoV-2, or if they've seen it, don't understand the difference between that and "Covid-19" and "coronavirus". Given this tool isn't aimed at medical professionals, I think the current wording is best practice. 

Certainly I haven't seen anyone use "SARS-CoV-2" except when I've been reading articles in medical journals and similar, which aren't intended to be looked at by a layperson.

In the UK, for example, [the government's online style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style) says

> **coronavirus (COVID-19)**
> 
> Coronavirus is the virus which causes the illness COVID-19. Coronavirus is lower case.

Likewise [the Guardian newspaper style guide](https://www.theguardian.com/guardian-observer-style-guide-c) says:

> **coronavirus outbreak 2019-20**
>
> The virus is officially called Sars-CoV-2 and this causes the disease Covid-19. However, for ease of communication we are following the same practice as the WHO and using **Covid-19** to refer to both the virus and the disease in our general reporting. It can also continue to be referred to as the coronavirus.

**Comment by catherio** [comment] 2020-11-03 23:00
Copying from the Whitepaper https://www.microcovid.org/paper/all#fn2_2

"Strictly speaking there is a difference between “getting SARS-CoV-2” (the virus itself) and “getting COVID-19” (the disease caused by the virus). In the rest of this article, no matter what language we use, we are talking about the total chance of getting infected, including if you show no symptoms and are an asymptomatic carrier of the virus. We chose to use “microCOVIDs” (referring to the disease) instead of “microCoV” (referring to the virus) for this article based on reader feedback that it was simpler and easier to understand. But we emphasize that we are not excluding asymptomatic infections from this measurement. "

**Comment by blanchardjeremy** [comment] 2020-11-03 23:34
Closing for now. Feel free to re-open if there's something that needs further consideration. :)

**Closed by blanchardjeremy** 2020-11-03 23:34 UTC

**Comment by saraedum** [comment] 2020-11-04 16:42
Thanks a lot for clarifying. Since I am not following the regular news in English that was not clear to me. In German, COVID would rarely be used by non-scientific press. The corresponding term to talk about disease and virus is "Corona" or equally "Coronavirus" so I'll use that.
