### ISSUE TITLE
"average person" risk isn't updating (Cook County IL and maybe other places)

### ISSUE THREAD

**Issue by raenforest** [microCOVID/microCOVID#1427] opened 2022-04-27 03:11 UTC
**Describe the bug**
I'm in Cook County IL. I check your site daily. 
In the section "Risk Profile: What is their risk profile?" - 
For the past few days, maybe a week or more,the "average person" risk level hasn't changed. It seems stuck at 3500, even though cases have been rising quickly. 
I think the other "Risk Profile" levels haven't been changing either, but I don't check those as often, so I'm not sure. 

**Link to microCOVID scenario**
If applicable, please copy-paste the URL to the scenario that you modeled on the calculator, so we can easily reproduce it.
https://www.microcovid.org/?distance=normal&duration=60&interaction=oneTime&personCount=4&riskBudget=1000&riskProfile=average&scenarioName=custom&setting=outdoor&subLocation=US_17031&theirMask=none&topLocation=US_17&voice=normal&yourMask=n95&yourVaccineDoses=2&yourVaccineType=pfizer

**To Reproduce**
Select IL, Cook County. 
Select "average person" risk level. 
It should be updating daily. But it's been at 3500 for several days, maybe a week or more. 

**Expected behavior**
Please fix it so that the "average person' risk level again updates daily, based on the current caseloads. 
Or, if there's some legitimate reason why the average person risk level isn't increasing even as cases increase, please explain that prominently. 

**Is this a regression?**
Yes, it was working before. It has been reliably adjusting to current case levels and trends, on a daily basis as far as I can tell, for as long as this tool has existed, as far as I know. I think there was one other time it seemed "stuck" like this, but I can't remember when. 

**Additional context / screenshots**
Add any other context about the problem here, including any screenshots.

**Comment by Meowse** [comment] 2022-04-29 01:33
If you click on the "> Details" link under "Step 1: Enter your location", you will see a line a few lines down that says, "Data last updated: **/**/****"

At the moment, for King County, WA, it says "Data last updated: 4/15/2022"
Same for Cook County, IL. And Taiwan.

I don't know why it's been so long -- but in the interim, the incidence in King County has almost doubled, and the positivity rate has increased significantly.

So I think the bug is "Covid risk data isn't being updated properly in multiple locations".

**Comment by Meowse** [comment] 2022-04-29 01:37
Probably a duplicate of https://github.com/microCOVID/microCOVID/issues/1426

**Comment by apiology** [comment] 2022-11-27 14:06
Presumably fixed by https://github.com/microCOVID/microCOVID/pull/1450.  Please file separate issues if you see any continuing issues.

**Closed by apiology** 2022-11-27 14:06 UTC
Labels: type: bug
