### ISSUE TITLE
Custom person risk in calculator

### ISSUE THREAD

**Issue by hmrm** [microcovid/microcovid#283] opened 2020-09-29 02:52 UTC
I'd like to use the advanced method to calculate risk for a few people, but I really like the calculator (particularly the fact that I don't need to input prevalence data to it and keep that up to date). In order to do this, I'd like to be able to select "custom" on the person risk profile, and have a box where I can put their number of microcovids in the past 9 days.

**Comment by blanchardjeremy** [comment] 2020-09-29 02:59
@hmrm interesting idea. 

In the meantime, you could just look at the percentage at the bottom of the activity risk section and multiply that by the person risk score. That will give you the total score.

![image](https://user-images.githubusercontent.com/32290/94507648-15271500-01c5-11eb-9e80-84a55fd5f3c2.png)

**Comment by hmrm** [comment] 2020-09-29 04:49
Excellent idea! I'll use that in the interim. Thanks!

**Comment by blanchardjeremy** [comment] 2020-11-08 02:47
We now have automatic location data import in the spreadsheet. So that aspect of this issue is handled.

And this is a duplicate of #16. Closing and redirecting us over there.

**Closed by blanchardjeremy** 2020-11-08 02:47 UTC
Labels: size: large/involved, skill: backend engineering, type: enhancement
