### ISSUE TITLE
Grocery shopping scenarios are way too cautious

### ISSUE THREAD

**Issue by linesarefuzzy** [microcovid/microcovid#648] opened 2021-01-14 21:49 UTC
I think modeling a trip to the grocery store as being near 10 people for an hour is way too cautious. Am I understanding it right that this is saying you're 6-10 feet from an average of 10 people at a time for a total of an hour? You might spend an hour in the store, but how much time are you within 15 feet of another human? I would say in an average store on an average day I'm within 15 feet of another human for maybe about 10 minutes cumulatively, and in those 10 minutes I'm rarely that close to more than one or maybe two humans at a time. It seems to me that modeling a grocery trip as 10 or 15 minutes 6 ft away from 2 or 3 people would be far more accurate and still erring on the side of caution. Just my (hopefully appropriately humble) opinion.

**Comment by blanchardjeremy** [comment] 2021-01-15 01:36
dupe of #649

**Closed by blanchardjeremy** 2021-01-15 01:36 UTC
