### ISSUE TITLE
Mixed Vaccine Schedule

### ISSUE THREAD

**Issue by rhrsyow** [microCOVID/microCOVID#1145] opened 2021-09-24 11:05 UTC
You may find this a minor point, but in Canada, many people between ages of 40 and 60 got the AstraZeneca vaccine, followed by either Pfizer or Moderna. Your calculator only allows you to input one vaccine, rather than a mixed series. I realize that there is limited trial data on this question, but I wish this could be added to your calculator.

**Comment by blanchardjeremy** [comment] 2021-09-24 13:51
Hi there. Thanks for this. 

This is a duplicate of #952

**Closed** 2021-09-24 13:51 UTC
Labels: duplicate, type: enhancement
