### ISSUE TITLE
Add vaccination status to risk profile

### ISSUE THREAD

**Issue by AnnaCPDX** [microcovid/microcovid#865] opened 2021-06-01 19:33 UTC
Could you add "fully vaccinated" to the risk profile drop down? Not sure how this would work for groups. For larger group sizes, could you add a way to include the % of the group that is fully vaccinated? (In OR this is available by zip code, even if you don't know the status of everyone near you.) Without this info, it is hard to use the calculator for situations that will happen all summer like "6 fully vaccinated adults outside and 6 unvaccinated children w/ or w/o masks"

**Comment by Hixie** [comment] 2021-06-04 22:27
Duplicate of https://github.com/microcovid/microcovid/issues/808?

**Comment by AnnaCPDX** [comment] 2021-06-04 23:10
I think probably yes. It just seems like it could be put in a lot of places in the calculator, even if a % of people fully vaccinated in my group or location is____ . Totally understand if this is not worth doing since location disease activity stats will eventually/soon-ish catch up with vaccination rates...

Thx!

**Comment by beshaya** [comment] 2021-06-08 01:03
Closing as duplicate of #808

**Closed by beshaya** 2021-06-08 01:03 UTC
