### ISSUE TITLE
“Copy link to this scenario” doesn’t work for manual prevalence data entry.

### ISSUE THREAD

**Issue by mattbell** [microcovid/microcovid#380] opened 2020-10-27 20:45 UTC
“Copy link to this scenario” doesn’t work for manual prevalence data entry.  Prevalence data is not copied.

**Comment by blanchardjeremy** [comment] 2020-10-28 05:10
@mattbell I'm wondering if this really is launch blocking. The current webpage actually doesn't have this feature either. I think it would be a good thing to fix soon, but I wonder if we need to wait until we fix it to move forward. Curious your thoughts.

**Comment by mattbell** [comment] 2020-10-28 05:28
OK -- if it's not trivial to fix, I'm happy letting it go.

**Comment by blanchardjeremy** [comment] 2020-10-28 16:26
Yeah. It's a medium sized task. Not huge but not a quick one line change.

**Comment by blanchardjeremy** [comment] 2020-10-29 05:16
Removing ux-redesign since the share by URL feature isn't exclusive to this release. It exists on the current site.

**Comment by blanchardjeremy** [comment] 2020-10-31 05:23
Duplicate of #345. Closing.

**Closed by blanchardjeremy** 2020-10-31 05:23 UTC
Labels: p1 important, size: small/easy
